name: Frontend CI

on:
  push:
    paths:
      - 'app/twenty4-seven/**'
    branches:
      - main
      - dev
      - '*'

jobs:
  build-and-test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.0'

      - name: Install dependencies
        run: |
          cd app/twenty4-seven
          yarn install --frozen-lockfile

      - name: Build project
        run: |
          cd app/twenty4-seven
          yarn build

      - name: Run tests
        run: |
          cd app/twenty4-seven
          yarn test